#libraries in correct order
library('R6')
library('data.table')
library('plyr')
library('dplyr')
library('stringr')
library('png')
library('grid')
library('ggplot2')
library('jsonlite')
library('svgR')
library('circular')
library('plyr')
library('CircStats')
library('ggExtra')
library('ggpubr')
library('R.matlab')
source(paste(getwd(),"R/Helpers/source-folder.R", sep = "/"))
source_folder(paste(getwd(),"R/Helpers/", sep = "/"))
source_folder(paste(getwd(),"R/Plotting/", sep = "/"))

